---
- name: Create default site plain http configuration
  template:
    src: '{{ item }}'
    dest: '/etc/nginx/sites-available/{{ inventory_hostname }}_http'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  with_first_found:
    - files:
        - 'files/nginx/sites/default_http.conf'
        - 'files/nginx/sites-available/default_http.conf.j2'
  notify:
    - Reload nginx
  tags:
    - configuration
    - nginx
    - sites


- name: Create default site tls https configuration
  template:
    src: '{{ item }}'
    dest: '/etc/nginx/sites-available/{{ inventory_hostname }}_tls'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  with_first_found:
    - files:
        - 'files/nginx/sites/default_tls.conf'
        - 'files/nginx/sites-available/default_tls.conf.j2'
  notify:
    - Reload nginx
  tags:
    - configuration
    - nginx
    - sites


- name: Enable default site plain http configuration
  file:
    src: '/etc/nginx/sites-available/{{ inventory_hostname }}_http'
    dest: '/etc/nginx/sites-enabled/{{ inventory_hostname }}_http'
    state: link
  notify:
    - Reload nginx
  tags:
    - configuration
    - nginx
    - sites


# Note: Done by acmetool after sucessfully obtaining a suitable certificate
#- name: Enable default site configuration
#  file:
#    src: '/etc/nginx/sites-available/{{ inventory_hostname }}_tls'
#    dest: '/etc/nginx/sites-enabled/{{ inventory_hostname }}_tls'
#    state: link
#  notify:
#    - Reload nginx
#  tags:
#    - configuration
#    - nginx
#    - sites
